stages:
  - install
  - test
  - build
  - update

variables:
  APP_NAME: digital-bank-backend
  ENV: staging

# Use a Maven image for build and test stages
install_stage:
  stage: install
  image: maven:3.9.9-ibm-semeru-21-jammy
  script:
    - mvn clean install -DskipTests=true
  artifacts:
    paths:
      - target/

test_stage:
  stage: test
  image: maven:3.9.9-ibm-semeru-21-jammy
  dependencies:
    - install_stage
  script:
    - echo "test not implemented yet"

build_stage:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" 
      > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "$CI_PROJECT_DIR"
      --dockerfile "$CI_PROJECT_DIR/Dockerfile"
      --destination "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"

update_stage:
  stage: update
  image:
    name: ubuntu:22.04
  before_script:
    - 'which ssh-agent || (apt-get update -y && apt-get install -y openssh-client git)'

    # Setup SSH directory
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa

    # Add GitLab.com to known_hosts to avoid authenticity prompt
    - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Start ssh-agent and add the key
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa

    # Configure Git identity
    - git config --global user.email "drissiisismail@gmail.com"
    - git config --global user.name "drissiisismail"

    - git clone git@gitlab.com:digitalbankingapp/digital-banking-app-helm-chart.git
    - cd digital-banking-app-helm-chart
    - ls -latr
  script:
    # Update Image TAG
    - sed -i "/^backend_image:/,/^[^ ]/ s|^\(\s*tag:\).*|\1 ${CI_COMMIT_SHORT_SHA}|" custom-values.yaml
    - cat custom-values.yaml
    - git add custom-values.yaml
    - git commit -am "Update Image"
    - git push

